import "./globals.css";
import Header from "../components/header/header";
import Footer from "../components/footer/footer";
import { Providers } from "@/redux/provider";

export const metadata = {
  title: "Meradji Abderrahim",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
